name: CI-test-trvais

on:
  push:
    branches: [test-trvais]
  pull_request:
    branches: [test-trvais]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        include:
          - rosetta_compile_option: "--enable-protocol-mpc-securenn"
            other: "other"
          - rosetta_compile_option: "--enable-protocol-mpc-securenn --enable-128bit"
            other: "others"
    steps:
      - name: Install basic dependencies
        run: sudo apt-get update
          # sudo apt-get -y install g++ cmake make automake
      - name: Install python dependencies
        run: python -m pip install --upgrade pip
          # pip install tensorflow==1.14.0 sklearn matplotlib
      - name: Before compile
        run: echo ${GITHUB_WORKSPACE} && ./rosetta.sh clean
      - name: Compile
        env:
          ROSETTA_COMPILE_OPTIONS: ${{ matrix.rosetta_compile_option }}
          OTHER: ${{ matrix.other }}
        run: echo "./rosetta.sh compile ${ROSETTA_COMPILE_OPTIONS} --enable-tests"
        # run: ./rosetta.sh compile $ROSETTA_COMPILE_OPTIONS --enable-tests
      # - name: Install
      #   run: ./rosetta.sh install
      # - name: Test modules
      #   run: ./rosetta.sh test all
      # - name: Test tutorials
      #   run: cd ./example/tutorials/code && bash ./tutorials.sh all
